# MAINTAINER "Michael Bradley" <michaelsbradleyjr@gmail.com>
# Ave, Regina Caelorum, ave, Domina Angelorum: salve, radix, salve, porta!

db:
  build: images/db
  env_file: env_file

wordpress:
  build: images/wordpress
  env_file: env_file
  links:
    - db:mysql
  ports:
    - "80:80"
    - "443:443"

sftp:
  build: images/sftp
  command: www-data::33
  ports:
    - "23456:22"
  volumes_from:
    - wordpress
